[versions]
androidx-activity = "1.7.0"
compose = "1.2.0"
compose-material3 = "1.0.0-alpha11"
espresso = "3.5.1"
gradle-plugin = "7.4.2"
junit = "4.13.2"
junit-android-ext = "1.1.5"
kotlin = "1.8.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
junit = { module = "junit:junit", version.ref = "junit" }
junit-android-ext = { module = "androidx.test.ext:junit", version.ref = "junit-android-ext" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }