[versions]
android-sdk-compile = "34"
android-sdk-min = "21"
androidx-activity = "1.8.2"
apollo-kotlin = "4.0.0-beta.4"
compose-jetpack = "1.5.8"
compose-multipatform = "1.6.0"
gradle-plugin = "8.2.0"
graphql-kotlin = "7.1.1"
java = "17"
kermit = "2.0.3"
koin = "3.6.0-alpha3"
komapper = "1.17.1"
kotlin = "1.9.22"
kotlinClothingWebshop = "1.0.0"
kotlin-dl = "0.5.2"
kotlinx-datetime = "0.6.0-RC.2"
ksp = "1.9.22-1.0.17"
ktor = "2.3.10"
slf4j = "2.0.13"
spring-security = "6.2.4"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
apollo-kotlin-runtime = { module = "com.apollographql.apollo3:apollo-runtime", version.ref = "apollo-kotlin" }
compose-jetpack-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-jetpack" }
compose-jetpack-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose-jetpack" }
graphql-kotlin-ktor-server = { module = "com.expediagroup:graphql-kotlin-ktor-server", version.ref = "graphql-kotlin" }
jclOverSlf4j = { module = "org.slf4j:jcl-over-slf4j", version.ref = "slf4j" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-koin = { module = "co.touchlab:kermit-koin", version.ref = "kermit" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
komapper-dialect-postgresql-r2dbc = { module = "org.komapper:komapper-dialect-postgresql-r2dbc", version.ref = "komapper" }
komapper-processor = { module = "org.komapper:komapper-processor", version.ref = "komapper" }
komapper-starter-r2dbc = { module = "org.komapper:komapper-starter-r2dbc", version.ref = "komapper" }
komapper-slf4j = { module = "org.komapper:komapper-slf4j", version.ref = "komapper" }
kotlin-dl-onnx = { module = "org.jetbrains.kotlinx:kotlin-deeplearning-onnx", version.ref = "kotlin-dl" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio-jvm", version.ref = "ktor" }
ktor-server-contentNegotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors-jvm", version.ref = "ktor" }
ktor-kotlinx-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
spring-security-crypto = { module = "org.springframework.security:spring-security-crypto", version.ref = "spring-security" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
apollo-kotlin = { id = "com.apollographql.apollo3", version.ref = "apollo-kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multipatform" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }