ktor {
  deployment {
    host = "0.0.0.0"
    port = 5400
  }
  application {
    modules = [ hu.bme.aut.ixnoyb.kotlinclothingwebshop.backend.ApplicationKt.module ]
  }
  postgresql {
    port = 5432
    port = ${?DATABASE_PORT}
    user = "postgres"
    user = ${?DATABASE_USER}
    password = "password"
    password = ${?DATABASE_PASSWORD}
    host = "localhost"
    host = ${?DATABASE_HOST_NAME}
  }
}

jwt {
  secret = "secret"
  secret = ${?JWT_SECRET}
//  issuer = "http://0.0.0.0:8080/"
//  audience = "http://0.0.0.0:8080/hello"
//  realm = "Access to 'hello'"
}